name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.solver }} tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.3'
        os:
          - ubuntu-latest
        arch:
          - x64
        solver:
          - SCS
          - ProxSDP
          - CSDP
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "::set-output name=folderschanged::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"
        id: folderschangedid
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
      - run: julia --project=${{ matrix.solver }} -e '
          using Pkg;
          Pkg.instantiate();'
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
      - run: julia --project=${{ matrix.solver }} ${{ matrix.solver }}/test.jl
        continue-on-error: true
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
