name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.3'
        os:
          - ubuntu-latest
        arch:
          - x64
        solver:
          - SCS
          - ProxSDP
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia --project=${{ matrix.solver }} -e '
          using Pkg;
          Pkg.instantiate();'
      - run: julia --project=${{ matrix.solver }} ${{ matrix.solver }}/test.jl
      - continue-on-error: true
