name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.3'
        os:
          - ubuntu-latest
        arch:
          - x64
        solver:
          - SCS
          - ProxSDP
    steps:
      - run: echo "::set-output name=folderschanged::$(git diff-tree --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ',')"
        id: folderschangedid
      - uses: actions/checkout@v2
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
      - run: julia --project=${{ matrix.solver }} -e '
          using Pkg;
          Pkg.instantiate();'
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
      - run: julia --project=${{ matrix.solver }} ${{ matrix.solver }}/test.jl
        continue-on-error: true
        if: contains(steps.folderschangedid.outputs.folderschanged, matrix.solver)
